CREATE DATABASE PROGRAMA;

CREATE TABLE ALUMNO(
    CODIGO VARCHAR (20) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CODIGO PRIMARY KEY (CODIGO)
);

CREATE TABLE DATOS_ALUMNO(
    CODIGO VARCHAR (20) NOT NULL,
    CURP VARCHAR(20) NOT NULL,
    APELLIDO_PATERNO VARCHAR (25) NOT NULL,
    APELLIDO_MATERNO VARCHAR (25) NOT NULL,
    NOMBRES VARCHAR (50) NOT NULL,
    FECHA_DE_NACIMIENTO VARCHAR(20) NOT NULL,
    CORREO_ELECTRONICO_1 VARCHAR(100) NOT NULL,
    CORREO_ELECTRONICO_2 VARCHAR(100),
    NUMERO_CELULAR_1 VARCHAR(10) NOT NULL,
    NUMERO_CELULAR_2 VARCHAR(10),
    NUMERO_TELEFONO_CASA VARCHAR(8),
    DIRECCION VARCHAR(100),
    NUMERO_EXTERIOR VARCHAR(10) NOT NULL,
    NUMERO_INTERIOR VARCHAR(10),
    COLONIA VARCHAR(100) NOT NULL,
    MUNICIPIO VARCHAR(100) NOT NULL,
    CODIGO_POSTAL VARCHAR(10),
    REFERENCIAS VARCHAR(1000),
    CONSTRAINT FK_CODIGO FOREIGN KEY(CODIGO) REFERENCES ALUMNO(CODIGO)
);

CREATE TABLE ASISTENCIAS(
    NUMERO_DE_ASISTENCIA INT AUTO_INCREMENT,
    CODIGO VARCHAR(20) NOT NULL,
    NOMBRE_DE_ALUMNO VARCHAR (100) NOT NULL,
    FECHA_DE_ENTRADA VARCHAR(20) NOT NULL,
    HORA_DE_ENTRADA VARCHAR(10),
    CONSTRAINT PK_NUMERO_DE_ASISTENCIA PRIMARY KEY (NUMERO_DE_ASISTENCIA)
);